(require 'auto-complete-config)
(ac-config-default)
(setq-default ac-sources '(ac-sources-words-in-all-buffer))
(setq ac-use-quick-help t)
(setq ac-quick-help-delay 1.0)
(setq ac-auto-start 4)
(setq ac-fuzzy-enable t)
(setq ac-use-comphist nil)
(provide 'init-complete)
