(add-hook 'python-mode-hook #'smartparens-mode)
(add-hook 'python-mode-hook #'rainbow-delimiters-mode)
(add-hook 'python-mode-hook #'lsp)
(add-hook 'python-mode-hook #'flycheck-mode)
(provide 'lang-python)
